### ISSUE TITLE
Request - export buildAttributeDecorator

### ISSUE THREAD

**Issue by aap82** [nathanstitt/mobx-decorated-models#1]
Is it possible to export the buildAttributeDecorator function from the property-decorator.js file so the library can be used without decorators as well?

A question: in the addAttribute function, you return an observable for each field, correct?  Is that returning  @field as a boxed value?  Sorry, I haven't tried this yet.

Thanks for this by the way.  It's pretty awesome, and should be a huge time saver.

**Comment by nathanstitt** [comment]
Hm, I took a look at this and exporting `buildAttributeDecorator` won't actually do what you want, but `addAttribute` would be closer.

However I attempted to export `addAttribute` and that didn't work since it doesn't have a descriptor to pass into mobx.

Really I'm a bit on the fence about this.  It'd be nice to support decorator-less behavior but only as long as it can be done without overly complicating the logic. 

Plus since "decorated" is in the name it seems  a little strange to support using it without decorators 😁 

FYI here's the spec i wrote to test, maybe it'll be helpful:

```javascript
import { autorun } from 'mobx';
import { addAttribute, field } from '../lib/property-decorators';

class PlainClassModel {

}

addAttribute(field, PlainClassModel, 'fieldTest');

describe('Mocking Models without Decorators', () => {
    it('adds methods', () => {
        const c = new PlainClassModel();
        const spy = jest.fn();
        autorun(() => spy(c.fieldTest));
        c.fieldTest = 'one';
        expect(spy).toHaveBeenCalledTimes(2); // fails because "fieldTest" isn't configured as an observable
    });
});
```
